openapi: 3.0.0
info:
  title: "Sample API"
  description: "API para personas y notas"
  version: "1.0.0"

paths:
  /people:
    get:
      summary: "Obtener lista de personas"
      responses:
        '200':
          description: "Lista de personas obtenida correctamente"

  /notes:
    get:
      summary: "Obtener lista de notas"
      responses:
        '200':
          description: "Lista de notas obtenida correctamente"
